name: flutter_iap
description: in app purchases for flutter
version: 1.2.0
author: Jack ODonnell <jackappdevinc@gmail.com>
homepage: https://github.com/JackAppDev/flutter_iap/

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.jackappdev.flutteriap
    pluginClass: FlutterIapPlugin